Add `/area near` command
FroobWorld/NabSuite pull request #8
Opened 2024-11-20 13:56 UTC by bonan

Adds the subcommand `/area near` for players with permission `nabsuite.command.area.near`.

If the player is inside an area that has subareas within the radius - those subareas will be shown instead of the parent area.

Default radius, max radius and max areas to display can be configured in `protect/config.yml`

2024-11-22 23:50 UTC, froobynooby requested changes
Looks good, just some suggestions

2024-11-22 23:50 UTC, froobynooby commented on src/main/java/com/froobworld/nabsuite/modules/protect/command/AreaCommand.java
> +                new AreaNearCommand(protectModule)
Could you move this below AreaHereCommand so it appears below it in the usage message?

2024-11-22 23:50 UTC, froobynooby commented on src/main/java/com/froobworld/nabsuite/modules/protect/command/AreaNearCommand.java
> +                                Component.text("(" + (a.distance == 0 ? "here" : (int)Math.ceil(a.distance)) + ")")
Could you maybe make this red so it stands out a bit more?

2024-11-23 00:45 UTC, bonan commented on src/main/java/com/froobworld/nabsuite/modules/protect/command/AreaNearCommand.java
> +                                Component.text("(" + (a.distance == 0 ? "here" : (int)Math.ceil(a.distance)) + ")")
![image](https://github.com/user-attachments/assets/b9a4ea03-86fb-4b05-a620-31f71c009049)

2024-11-23 00:51 UTC, froobynooby commented on src/main/java/com/froobworld/nabsuite/modules/protect/command/AreaNearCommand.java
> +                                Component.text("(" + (a.distance == 0 ? "here" : (int)Math.ceil(a.distance)) + ")")
I was thinking other way around, but that also works

2024-11-23 00:57 UTC, bonan commented on src/main/java/com/froobworld/nabsuite/modules/protect/command/AreaCommand.java
> +                new AreaNearCommand(protectModule)
Fixed

2024-11-23 00:57 UTC, bonan commented on src/main/java/com/froobworld/nabsuite/modules/protect/command/AreaNearCommand.java
> +                                Component.text("(" + (a.distance == 0 ? "here" : (int)Math.ceil(a.distance)) + ")")
Fixed it so the area name is in red now

2024-11-23 01:02 UTC, froobynooby commented
Thanks

2024-11-23 01:02 UTC, merged